version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  hello-node:
    lang: node22
    handler: ./hello-node
    image: <account-id>.dkr.ecr.eu-west-1.amazonaws.com/hello-node:latest
    imagePullSecrets:
      - ecr-registry-secret